project/config/routes.rb
Rails.application.routes.draw do

    scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
      root to: 'feed#index_articles_feed'
      resources :article
      resources :category
      devise_for :customers
      get '/customers', to: redirect('/customers/sign_up')
      scope '/feed' do
        get 'articles', to: 'feed#index_articles_feed', as: 'index_articles_feed'
        get 'categories', to: 'feed#index_categories_feed', as: 'index_categories_feed'
        get 'articles/:id', to: 'feed#show_article_feed', as: 'show_article_feed'
        get 'categories/:id', to: 'feed#show_category_feed', as: 'show_category_feed'
        get 'search', to: 'search#search_article_result'
      end
  
      namespace :admin do
        resources :management_article
        resources :management_category
        resources :management_customer do
          patch :toggle_active, on: :member
          get :show_modal, on: :member
        end
        get 'management_customer/index'
      end
    end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
  

project/app/views/navigations/_feed.html.haml
%a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
  = I18n.t('navigations.feeds')
  %span.caret
%ul.dropdown-menu
  %li
    = link_to I18n.t('navigations.article'), index_articles_feed_path
  %li
    = link_to I18n.t('navigations.category'), index_categories_feed_path

project/app/views/navigations/_locale.haml
%a.dropdown-toggle.navbar-right{"data-toggle" => "dropdown", :href => "#"}
  %i.fa-solid.fa-language
%ul.dropdown-menu
  %li{class: ('active' if current_locale?(:vn))}
    = link_to 'VN', locale: "vn"
  %li{class: ('active' if current_locale?(:en))}
    = link_to 'EN', locale: "en"

project/app/views/navigations/_nav.html.haml
%nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
    - if customer_signed_in?
      = render display_role(current_customer.role_id)
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to current_customer.last_name, edit_customer_registration_path
        %li
          = link_to I18n.t('navigations.log_out'), destroy_customer_session_path, method: :delete
        %li.dropdown
          = render 'navigations/locale'
      = render 'search/search_article'
    - else
      %a.navbar-brand{href: root_path} 📚 BlogBook
      %ul.nav.navbar-nav
        %li.dropdown{class: ('active' if current_controller?('feed'))}
          = render 'navigations/feed'
      %ul.nav.navbar-nav.navbar-right
        %li
          = link_to I18n.t('navigations.sign_in'), new_customer_session_path
        %li
          = link_to I18n.t('navigations.sign_up'), new_customer_registration_path
        %li.dropdown
          = render 'navigations/locale'
      = render 'search/search_article'

project/app/views/navigations/_nav_admin.html.haml
%a.navbar-brand{href: root_path} 📚 Admin
%ul.nav.navbar-nav
  %li.dropdown{class: ('active' if current_controller?('feed'))}
    = render 'navigations/feed'
  %li{class: ('active' if current_controller?('management_article'))}
    %a{href: admin_management_article_index_path}
      = I18n.t('navigations.management_article')
  %li{class: ('active' if current_controller?('management_category'))}
    %a{href: admin_management_category_index_path}
      = I18n.t('navigations.management_category')
  %li{class: ('active' if current_controller?('management_customer'))}
    %a{href: admin_management_customer_index_path}
      = I18n.t('navigations.management_customer')

project/app/views/navigations/_nav_customer.html.haml
%a.navbar-brand{href: root_path}
  %span 📚
  = I18n.t('customer')
%ul.nav.navbar-nav
  %li.dropdown{class: ('active' if current_controller?('feed'))}
    = render 'navigations/feed'
  %li{class: ('active' if current_controller?('article'))}
    %a{href: article_index_path} 
      =I18n.t('my_article')
  %li{class: ('active' if current_controller?('category'))}
    %a{href: category_index_path}
      =I18n.t('my_category')