project/config/routes.rb
Rails.application.routes.draw do

    scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
      root to: 'feed#index_articles_feed'
      resources :article
      resources :category
      devise_for :customers
      get '/customers', to: redirect('/customers/sign_up')
      scope '/feed' do
        get 'articles', to: 'feed#index_articles_feed', as: 'index_articles_feed'
        get 'categories', to: 'feed#index_categories_feed', as: 'index_categories_feed'
        get 'articles/:id', to: 'feed#show_article_feed', as: 'show_article_feed'
        get 'categories/:id', to: 'feed#show_category_feed', as: 'show_category_feed'
        get 'search', to: 'search#search_article_result'
      end
  
      namespace :admin do
        resources :management_article
        resources :management_category
        resources :management_customer do
          patch :toggle_active, on: :member
          get :show_modal, on: :member
        end
        get 'management_customer/index'
      end
    end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
  

project/app/controllers/admin/management_category_controller.rb
# frozen_string_literal: true

module Admin
    # management of all categories of customer
    class ManagementCategoryController < AdminController
      def index
        @categories = paginate_item_desc(Category.all)
        @categories_with_article_count = count_articles_by_category
      end
  
      def show
        @category = find_category
        @articles = paginate_item_desc(Article.where(category_id: params[:id]))
      end
  
      # edit
      def edit
        @category = find_category
      end
  
      def update
        @category = find_category
        if @category.update(category_params)
          flash[:notice] = I18n.t('notice.update_success')
          redirect_to admin_management_category_index_path
        else
          flash[:error] = I18n.t('notice.error')
          render :edit, status: :unprocessable_entity
        end
      end
  
      # delete
      def destroy
        @category = find_category
        @category.destroy
        redirect_to admin_management_category_index_path, notice: I18n.t('notice.delete_success')
      end
  
      # common
  
      private
  
      def find_category
        Category.find(params[:id])
      end
  
      def category_params
        params.require(:category).permit(:title, :content, :share_mode)
      end
    end
  end
  

project/app/views/admin/management_category/_form.html.haml
= form_with(model: category, url: path, html: {class: 'well form-horizontal'}, local: true) do |form|
  = render "devise/shared/error_messages", resource: category
  .form-group
    %label.col-md-2.control-label
      = I18n.t('category.title')
    .col-md-10.inputGroupContainer
      .input-group
        %span.input-group-addon
          %i.fa-solid.fa-t
        = form.text_field :title, class: 'form-control', placeholder: '140 characters maximum'
  .form-group
    %label.col-md-2.control-label
      = I18n.t('category.content')
    .col-md-10.inputGroupContainer
      .input-group
        %span.input-group-addon
          %i.fa-solid.fa-pen-nib
        = form.text_area :content, class: 'form-control', placeholder: '300 characters maximum'
  .form-group
    %label.col-md-2.control-label
      = I18n.t('category.share_mode')
    .col-md-10.inputGroupContainer
      .input-group
        = form.select :share_mode, ['public', 'private'], { selected: category.share_mode || 'public' }, class: 'form-control'
  %div
    = form.submit I18n.t('category.save_category'), class: 'btn btn-new'
    - if action_name == 'edit'
      = link_to admin_management_category_path(category),method: :delete, class: "btn btn-delete", data: { confirm: "Are you sure?" } do
        %i.fa-solid.fa-trash

project/app/views/admin/management_category/edit.html.haml
.container
  %table.table.table-striped
    %tbody
      %tr
        %td
          = render 'form',category: @category, path: admin_management_category_path

project/app/views/admin/management_category/index.html.haml
.container
  .row
    .well
      %h1.text-center
        = I18n.t('navigations.management_category')
      .cards_category
        - @categories.each do |category|
          .col-md-3.col-xs-5
            .card_content
              %a.card-category_link{:href => admin_management_category_path(category)}
              %h4.card_heading.text-truncate-container
                = category.title
              .card_body.text-truncate
                %p
                  = category.content
              .author.card-category_author
                %span.name
                  %i.fa-solid.fa-user
                  = category.customer.full_name
              .card-category_tag-share-mode
                = share_mode_show(category.share_mode)
              .card-category_tag-count-article
                = @categories_with_article_count[category.id] || 0
                %i.fa-solid.fa-newspaper
              = link_to I18n.t('edit'), edit_admin_management_category_path(category), class: "btn btn-default card-caterory_edit"
            
      = will_paginate @categories

project/app/views/admin/management_category/show.html.haml
.container
  .row
    .well
      %h1.text-center Category
      .list-group
        - @articles.each do |article|
          .articles
            %a.list-group-item.vertical-center.article-link{href: admin_management_article_path(article)}
              .media.col-md-3
                %figure
                  - if article.image_url.present?
                    = image_tag(article.image_url, class: "img-rounded img-responsive img-fit" )
                  - else
                    = image_tag('http://via.placeholder.com/350x250', class: "media-object img-rounded img-responsive")
              .col-md-6.text-truncate-container 
                %h4.list-group-item-heading
                  = truncate(article.title, length: 50)
                = share_mode_show(article.share_mode)
                %p.list-group-item-text.text-truncate
                  = truncate(article.short_description, length: 200)
                  .author
                    %span.name.text-truncate
                      %i.fa-solid.fa-user
                      = article.customer.full_name
                      = article.created_at
            .text-center.article-buttons
              = link_to I18n.t('edit'), edit_admin_management_article_path(article), class: "btn btn-default btn-block button"
              = link_to I18n.t('delete'), admin_management_article_path(article),method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-block button"
            .article-id
              = article.id
          .clearfix
      = will_paginate @articles