project/config/routes.rb
Rails.application.routes.draw do

    scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
      root to: 'feed#index_articles_feed'
      resources :article
      resources :category
      devise_for :customers
      get '/customers', to: redirect('/customers/sign_up')
      scope '/feed' do
        get 'articles', to: 'feed#index_articles_feed', as: 'index_articles_feed'
        get 'categories', to: 'feed#index_categories_feed', as: 'index_categories_feed'
        get 'articles/:id', to: 'feed#show_article_feed', as: 'show_article_feed'
        get 'categories/:id', to: 'feed#show_category_feed', as: 'show_category_feed'
        get 'search', to: 'search#search_article_result'
      end
  
      namespace :admin do
        resources :management_article
        resources :management_category
        resources :management_customer do
          patch :toggle_active, on: :member
          get :show_modal, on: :member
        end
        get 'management_customer/index'
      end
    end
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end
  

project/app/models/article.rb
# frozen_string_literal: true

# Represents an article in the application.

require 'elasticsearch/model'
class Article < ApplicationRecord
  include ArticleImageUploader::Attachment(:image)
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks
  
  acts_as_paranoid
  belongs_to :customer
  belongs_to :category, optional: true

  validates :title, presence: true, length: { maximum: 140 }
  validates :short_description, presence: true, length: { maximum: 300 }
  validates :content, presence: true
  validates :category_id, presence: true, allow_nil: true
  
  settings do
    mappings dynamic: 'false' do
      indexes :title, type: 'text'
      indexes :content, type: 'text'
    end
  end
  
  def private_mode?
    share_mode == 'private'
  end

  def public_mode?
    share_mode == 'public'
  end

  def self.filtered_articles
    joins("LEFT OUTER JOIN categories ON articles.category_id = categories.id")
    .joins("INNER JOIN customers ON articles.customer_id = customers.id")
    .where("categories.share_mode = ? OR categories.id IS NULL", "public")
    .where("articles.share_mode = ? AND customers.active = ?", "public", true)
  end
end

Article.import

project/app/controllers/article_controller.rb
# frozen_string_literal: true

# control action on an article of customer
class ArticleController < ApplicationController
    before_action :authenticate_customer!, except: [:show]
    def index
      @articles = current_customer.articles.paginate(page: params[:page], per_page: 2).order(created_at: :desc)
    end
  
    def show
      @article = find_article
    end
  
    # create
    def new
      @article = current_customer.articles.build
      @categories = categories_get
    end
  
    def create
      @article = current_customer.articles.build(article_params)
      @categories = categories_get
      if @article.save
        redirect_to @article, notice: I18n.t('notice.create_success')
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    # edit
    def edit
      @article = find_article
      @categories = categories_get
    end
  
    def update
      @article = find_article
      @categories = categories_get
      if @article.update(article_params)
        flash[:notice] = I18n.t('notice.update_success')
        redirect_to @article
      else
        flash[:error] = I18n.t('notice.error')
        render :edit, status: :unprocessable_entity
      end
    end
  
    # delete
    def destroy
      @article = find_article
      @article.destroy
  
      redirect_to article_index_path, notice: I18n.t('notice.delete_success')
    end
  
    # common
  
    private
  
    def find_article
      current_customer.articles.find(params[:id])
    end
  
    def categories_get
      current_customer.categories
    end
  
    def article_params
      params.require(:article).permit(:title, :content, :short_description, :share_mode, :image, :category_id)
    end
  end
  

project/app/views/article/_form.hmt.haml
= form_with(model: article, url: path, html: {class: 'well form-horizontal'}, local: true) do |form|
  = render "devise/shared/error_messages", resource: article
  .form-group
    %label.col-md-2.control-label
      = I18n.t('article.title')
    .col-md-10.inputGroupContainer
      .input-group
        %span.input-group-addon
          %i.fa-solid.fa-t
        = form.text_field :title, class: 'form-control', placeholder: I18n.t('characters_maximum', maximun: 140)
  .form-group
    %label.col-md-2.control-label
      = I18n.t('article.short_description')
    .col-md-10.inputGroupContainer
      .input-group
        %span.input-group-addon
          %i.fa-solid.fa-heading
        = form.text_field :short_description, class: 'form-control', placeholder: I18n.t('characters_maximum', maximun: 300)
  .form-group
    %label.col-md-2.control-label
      = I18n.t('article.content')
    .col-md-10.inputGroupContainer
      .input-group
        %span.input-group-addon
          %i.fa-solid.fa-pen-nib
        = form.text_field :content, class: 'quill_container'
  .form-group
    %label.col-md-2.control-label
      = I18n.t('article.category')
    .col-md-10.inputGroupContainer
      
      .input-group
        - options = options_for_select([['None', nil]] + categories.map { |c| [c.title, c.id] }, selected: article.category_id)
        = form.select :category_id, options, {}, class: 'form-control'
  .form-group
    %label.col-md-2.control-label
      = I18n.t('article.image')
    .col-md-10.inputGroupContainer
      .input-group
        = form.hidden_field :image, value: article.cached_image_data
        = form.file_field :image, onchange: 'previewImage(event)'# Thêm thuộc tính `direct: true` nếu bạn muốn tải lên trực tiếp
        - if article.image_url.present?
          = image_tag(article.image_url, class: "media-object img-rounded img-responsive img-fit", id: 'image_data' )
          %br
            %img#image_preview.img-responsive.img-fit
          %br
        - else
          %br
            %img#image_preview.img-responsive.img-fit
          %br
  .form-group
    %label.col-md-2.control-label
      = I18n.t('article.share_mode')
    .col-md-10.inputGroupContainer
      .input-group
        = form.select :share_mode, ['public', 'private'], { selected: article.share_mode || 'public' }, class: 'form-control'
  
  %div
    = form.submit I18n.t('article.save_article'), class: 'btn btn-new'

project/app/views/article/edit.hmt.haml
%h1 Article#edit
.container
  %table.table.table-striped
    %tbody
      %tr
        %td
          = render 'form', article: @article, categories: @categories, path: article_path

project/app/views/article/index.hmt.haml
.container
  .row
    .well
      %h1.text-center
        = I18n.t('my_article')
      %a.btn-new{href: new_article_path, role: "button"}
        = I18n.t('article.new_article')
      .list-group
        - @articles.each do |article|
          .articles
            %a.list-group-item.vertical-center.article-link{href: article_path(article,locale: I18n.locale)}
              .media.col-md-3
                %figure
                  - if article.image_url.present?
                    = image_tag(article.image_url, class: "img-rounded img-responsive img-fit" )
                  - else
                    = image_tag('http://via.placeholder.com/350x250', class: "media-object img-rounded img-responsive")
              .col-md-6.text-truncate-container 
                %h4.list-group-item-heading
                  = truncate(article.title, length: 50)
                = share_mode_show(article.share_mode)
                %p.list-group-item-text.text-truncate
                  = truncate(article.short_description, length: 200)
            .text-center.article-buttons
              = link_to I18n.t('edit'), edit_article_path(article), class: "btn btn-default btn-block button"
              = link_to I18n.t('delete'), article_path(article),method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-block button"
            .article-id
              = article.id
          .clearfix
      = will_paginate @articles

project/app/views/article/new.hmt.haml
 .container
  %table.table.table-striped
    %tbody
      %tr
        %td
          = render 'form',article: @article, categories: @categories, path: article_index_path

= javascript_include_tag 'preview_image'

project/app/views/article/show.hmt.haml
.container
  .panel.panel-default
    .panel-heading
      .row
        .col-md-9
          %a{:href => "#"}
            = current_customer.full_name
            %br
          = share_mode_show(@article.share_mode)
        .col-md-3.text-center
          = link_to I18n.t('edit'), edit_article_path(@article), class: "btn btn-default"
          = link_to I18n.t('delete'), article_path(@article),method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"
    .panel-body
      - if @article.image_url.present?
        = image_tag(@article.image_url, class: "media-object img-responsive img-article" )
      - else
        = image_tag('http://via.placeholder.com/350x250', class: "img-responsive img-article")
      .row
        .col-md-12
          %h2.text-uppercase
            = @article.title
          %h5.text-monospace
            = @article.short_description
          %p
            = raw @article.content
          .clearfix